Repository Catappult/appcoins-wallet-android, pull requests merged in 2023-10, with the labels that each got.

#741 [APPC-3892]Add OEM ID to payment methods
  app/src/main/java/com/asfoundation/wallet/App.kt
  app/src/main/java/com/asfoundation/wallet/di/temp_gradle_modules/BdsBillingModule.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetFirstPaymentMethodsUseCase.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/BrokerBdsApi.kt
  legacy/bdsbilling/build.gradle.kts
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BdsBilling.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingRepository.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
  legacy/billing/build.gradle.kts
  legacy/billing/src/main/java/com/appcoins/wallet/billing/AppcoinsBillingReceiverActivity.kt
  legacy/billing/src/main/java/com/appcoins/wallet/billing/BillingDependenciesProvider.kt
  legacy/billing/src/main/java/com/appcoins/wallet/billing/BillingService.kt
Labels: Priority

#744 Change top up success icon
  ui/common/src/main/res/raw/top_up_bonus_success_animation.json
Labels: Feature Branch

#751 Fix bug recovering wallet
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: Priority, Bug

#756 Topup methods selection
  app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentView.kt
  app/src/main/java/com/asfoundation/wallet/topup/paymentMethods/TopUpPaymentMethodsAdapter.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/TopupPaymentMethodsViewHolder.kt
  app/src/main/res/layout-land/fragment_top_up.xml
  app/src/main/res/layout/fragment_top_up.xml
  app/src/main/res/layout/item_top_value.xml
  app/src/main/res/layout/item_topup_payment_method.xml
  app/src/main/res/layout/skeleton_payments_dark.xml
  app/src/main/res/layout/skeleton_rounded_rectangle_dark.xml
  app/src/main/res/layout/view_purchase_bonus_dark.xml
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
  legacy/skills/src/main/res/drawable/ic_topup_error.xml
  legacy/skills/src/main/res/drawable/topup_background_method_selected.xml
  legacy/skills/src/main/res/values/colors.xml
  ui/common/src/main/res/drawable/rectangle_blue_secondary_radius_16dp.xml
  ui/common/src/main/res/values/colors.xml
  ui/common/src/main/res/values/styles.xml
Labels: Feature Branch

#755 Feature/topup adyen fragments
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
  app/src/main/res/layout-land/fragment_adyen_top_up.xml
  app/src/main/res/layout/fragment_adyen_top_up.xml
  app/src/main/res/layout/view_purchase_bonus.xml
Labels: Payments v3, Feature Branch

#763 [Fix][APPC-3924] Fix design issues
  app/build.gradle.kts
  app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
  app/src/main/res/layout/home_manage_wallet_bottom_sheet_layout.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  gradle/libs.versions.toml
  ui/common/src/main/res/drawable/ic_app_logo_icon.xml
  ui/common/src/main/res/drawable/ic_launcher_background.xml
  ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsGamificationComposable.kt
Labels: Priority, Bug

#773 [APPC-3939] Fix overlapping button on pre-selected payment method screen
  app/src/main/res/layout/payment_methods_layout.xml
Labels: Payments v3, ReadyForMerge

#771 [APCC-3930][Fix] Change navigation from recover to NavBar instead to home_graph
  app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
  app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt
  app/src/main/res/navigation/recover_wallet_graph.xml
Labels: Priority, ReadyForMerge

#762 New Crowdin updates
  legacy/skills/src/main/res/values-fa-rIR/strings.xml
  legacy/skills/src/main/res/values-pl-rPL/strings.xml
  legacy/skills/src/main/res/values-zh-rCN/strings.xml
  ui/common/src/main/res/values-ar/strings.xml
  ui/common/src/main/res/values-bg/strings.xml
  ui/common/src/main/res/values-bn/strings.xml
  ui/common/src/main/res/values-de/strings.xml
  ui/common/src/main/res/values-el/strings.xml
  ui/common/src/main/res/values-es/strings.xml
  ui/common/src/main/res/values-fa/strings.xml
  ui/common/src/main/res/values-fr/strings.xml
  ui/common/src/main/res/values-hi/strings.xml
  ui/common/src/main/res/values-hu/strings.xml
  ui/common/src/main/res/values-in/strings.xml
  ui/common/src/main/res/values-it/strings.xml
  ui/common/src/main/res/values-ja/strings.xml
  ui/common/src/main/res/values-ko/strings.xml
  ui/common/src/main/res/values-mr/strings.xml
  ui/common/src/main/res/values-ms/strings.xml
  ui/common/src/main/res/values-my/strings.xml
  ui/common/src/main/res/values-nl/strings.xml
  ui/common/src/main/res/values-pa/strings.xml
  ui/common/src/main/res/values-pl/strings.xml
  ui/common/src/main/res/values-pt-rBR/strings.xml
  ui/common/src/main/res/values-pt/strings.xml
  ui/common/src/main/res/values-ro/strings.xml
  ui/common/src/main/res/values-ru/strings.xml
  ui/common/src/main/res/values-sr/strings.xml
  ui/common/src/main/res/values-th/strings.xml
  ui/common/src/main/res/values-tr/strings.xml
  ui/common/src/main/res/values-uk/strings.xml
  ui/common/src/main/res/values-vi/strings.xml
  ui/common/src/main/res/values-zh-rCN/strings.xml
  ui/common/src/main/res/values-zh-rTW/strings.xml
Labels: ReadyForMerge

#772 Strings Update - Gamification (APPC-3916)
  ui/common/src/main/res/values/strings.xml
Labels: ReadyForMerge

#778 [APPC-3924] Fix layout issues
  legacy/skills/src/main/res/values/colors.xml
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/TransactionsComposable.kt
Labels: Bug, ReadyForMerge

#782 [APCC-3927]: Fix Crash on BillingWebViewFragment
  app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
Labels: Priority, Bug

#775 [ESKL-335] Leaderboard reward improvement
  core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/api/BonusPrizeApi.kt
  legacy/skills/src/main/java/cm/aptoide/skills/endgame/SkillsEndgameFragment.kt
  legacy/skills/src/main/java/cm/aptoide/skills/endgame/SkillsEndgameViewModel.kt
  legacy/skills/src/main/java/cm/aptoide/skills/endgame/rankings/RankingsContentFragment.kt
  legacy/skills/src/main/java/cm/aptoide/skills/endgame/rankings/RankingsPagerAdapter.kt
  legacy/skills/src/main/java/cm/aptoide/skills/endgame/rankings/SkillsRankingsFragment.kt
  legacy/skills/src/main/java/cm/aptoide/skills/repository/BonusRepository.kt
  legacy/skills/src/main/java/cm/aptoide/skills/usecase/GetRewardsPackagesUseCase.kt
Labels: Priority, E-Skills

#798 fix(APPC-3987) Prevent duplicated appc requests
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Labels: Priority

#797 fix(APPC-3988) Stored card option update
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
Labels: Priority

#774 [APPC-3848] Action URLs for games bundle
  app/src/main/java/com/asfoundation/wallet/home/usecases/GetGamesListingUseCase.kt
  app/src/main/java/com/asfoundation/wallet/repository/GamesRepository.kt
  app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
  app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
  app/src/test/java/com/asfoundation/wallet/home/usecases/GetGamesListingUseCaseTest.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/GamesApi.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/GamesListingResponseItem.kt
  ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
  ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/OpenGameFunction.kt
  ui/widgets/src/gp/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
  ui/widgets/src/gp/java/com/appcoins/wallet/ui/widgets/OpenGameFunction.kt
Labels: Priority
