Repository Catappult/appcoins-wallet-android, pull requests merged in 2023-09, with the labels that each got.

#688 New Crowdin updates
  ui/common/src/main/res/values-fr/strings.xml
Labels: Strings

#681 Fix main crash of GP console (binding)
  app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
Labels: Bug

#685 adds check for lateinit
  core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/model/TicketResponse.kt
  legacy/skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt
Labels: E-Skills, Bug

#692 [Feature/APPC-3580] recovery wallet
  app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogFragment.kt
  app/src/main/java/com/asfoundation/wallet/my_wallets/create_wallet/CreateWalletDialogViewModel.kt
  app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryFragment.kt
  app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
  app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordFragment.kt
  app/src/main/java/com/asfoundation/wallet/recover/password/RecoverPasswordNavigator.kt
  app/src/main/java/com/asfoundation/wallet/recover/result/RecoverEntryResult.kt
  app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt
  app/src/main/res/layout-land/fragment_rating_negative.xml
  app/src/main/res/layout-land/recover_entry_fragment.xml
  app/src/main/res/layout-land/recover_password_fragment.xml
  app/src/main/res/layout/fragment_rating_negative.xml
  app/src/main/res/layout/recover_entry_fragment.xml
  app/src/main/res/layout/recover_entry_options.xml
  app/src/main/res/layout/recover_password_fragment.xml
  app/src/main/res/layout/recover_password_info.xml
  app/src/main/res/layout/recovery_wallet_success_bottom_sheet_layout.xml
  app/src/main/res/navigation/recover_wallet_graph.xml
  ui/common/src/main/java/com/appcoins/wallet/ui/common/MultilineInputText.kt
  ui/common/src/main/res/drawable/recovery_entry.xml
  ui/common/src/main/res/layout/multiline_input_layout.xml
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WalletTextFieldView.kt
Labels: Milestone2

#710 Fix/error crating wallet intercom firebase updates
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/asfoundation/wallet/backup/BackupEntryNavigator.kt
  app/src/main/java/com/asfoundation/wallet/onboarding/gp_install/OnboardingGPInstallNavigator.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/OnboardingPaymentMethodsNavigator.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultNavigator.kt
  convention/src/main/java/com/appcoins/wallet/convention/plugins/FirebasePlugin.kt
  feature/support/data/src/main/java/com/wallet/appcoins/feature/support/data/SupportRepository.kt
  gradle/libs.versions.toml
Labels: Bug

#712 Fix remove wallet crash
  app/src/main/java/com/asfoundation/wallet/manage_wallets/RemoveWalletFragment.kt
  app/src/main/java/com/asfoundation/wallet/my_wallets/main/MyWalletsNavigator.kt
Labels: Bug

#713 BugFix/ Recovery Navigate Back Error
  app/src/main/java/com/asfoundation/wallet/recover/entry/RecoverEntryNavigator.kt
  app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt
Labels: Bug

#721 [APPC-3895][Bug] fix verify button hidden on IAP
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
Labels: Bug

#727 Adds wallet creation flow to eskills activity calls
  app/src/main/java/com/asfoundation/wallet/ui/OneStepPaymentReceiver.kt
Labels: Priority, E-Skills

#726 [APPC-3708] Adds oemid to CreditsPurchaseBody
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/CreditsPurchaseBody.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Labels: E-Skills
