Repository Catappult/appcoins-wallet-android, pull requests merged in 2023-12, with the labels that each got.

#852 feat(ESKL-383): add foregroundServiceType to BackgroundGameService
  legacy/skills/src/main/AndroidManifest.xml
Labels: Priority

#857 feat(ESKL-383): add version check and specific foregroundStart
  legacy/skills/src/main/java/cm/aptoide/skills/games/BackgroundGameService.kt
Labels: Priority, E-Skills

#858 [APPC-4045] OemId to Indicative events
  app/src/main/java/com/asfoundation/wallet/topup/TopUpFragmentPresenter.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/confirm/CarrierFeePresenter.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/verify/CarrierVerifyPresenter.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/OemIdExtractorV2.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/PartnerAddressService.kt
  core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OemIdPreferencesDataSource.kt
Labels: Priority

#811 [APPC-3908] Fix hidden buttons on on IAP to small devices
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/payments/common/PurchaseBonusView.kt
  app/src/main/res/layout-land/adyen_credit_card_layout.xml
  app/src/main/res/layout-land/adyen_credit_card_pre_selected.xml
  app/src/main/res/layout-land/fragment_share_payment_link.xml
  app/src/main/res/layout-land/payment_methods_header.xml
  app/src/main/res/layout-land/payment_methods_layout.xml
  app/src/main/res/layout/selected_payment_method_cc.xml
Labels: Priority, Bug

#843 [APPC-4053] Remove billing address code
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressData.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressFragment.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressModel.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressModule.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressNavigator.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressPresenter.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressRepository.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressTextWatcher.kt
  app/src/main/java/com/asfoundation/wallet/billing/address/BillingAddressView.kt
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentFragment.kt
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentPresenter.kt
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentView.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_result/OnboardingPaymentResultViewModel.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpActivity.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpActivityView.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpAnalytics.kt
  app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpData.kt
  app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpFragment.kt
  app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpModule.kt
  app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpNavigator.kt
  app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpPresenter.kt
  app/src/main/java/com/asfoundation/wallet/topup/address/BillingAddressTopUpView.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
  app/src/main/res/layout-land/fragment_billing_address.xml
  app/src/main/res/layout-land/fragment_billing_address_top_up.xml
  app/src/main/res/layout-land/layout_billing_address.xml
  app/src/main/res/layout/fragment_billing_address.xml
  app/src/main/res/layout/fragment_billing_address_top_up.xml
  app/src/main/res/layout/layout_billing_address.xml
  app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
  app/src/test/java/com/asfoundation/wallet/ui/iab/InAppSubscriptionPurchaseResponseInteractorTest.java
  app/src/test/java/com/asfoundation/wallet/util/CurrencyFormatUtilsTest.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/AdyenBillingAddress.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/AdyenPayment.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/TokenPayment.kt
  legacy/billing/src/main/java/com/appcoins/wallet/billing/ErrorInfo.kt
  legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/AdyenPaymentRepository.kt
  legacy/billing/src/main/java/com/appcoins/wallet/billing/adyen/Payment.kt
  legacy/billing/src/main/java/com/appcoins/wallet/billing/common/BillingErrorMapper.kt
  legacy/billing/src/test/java/com/appcoins/wallet/billing/BillingErrorMapperTest.kt
  ui/common/src/main/res/values/styles.xml
Labels: Priority

#805 [APPC-3969] Sandbox payments for developers
  app/src/main/java/com/asfoundation/wallet/billing/adyen/PaymentType.java
  app/src/main/java/com/asfoundation/wallet/billing/sandbox/SandboxFragment.kt
  app/src/main/java/com/asfoundation/wallet/billing/sandbox/SandboxNavigator.kt
  app/src/main/java/com/asfoundation/wallet/billing/sandbox/SandboxViewModel.kt
  app/src/main/java/com/asfoundation/wallet/billing/sandbox/repository/SandboxRepository.kt
  app/src/main/java/com/asfoundation/wallet/billing/sandbox/usecases/CreateSandboxTransactionUseCase.kt
  app/src/main/java/com/asfoundation/wallet/billing/sandbox/usecases/WaitForSuccessSandboxUseCase.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/payment_methods/list/model/PaymentMethodModel.kt
  app/src/main/java/com/asfoundation/wallet/transactions/TransactionModel.kt
  app/src/main/java/com/asfoundation/wallet/transactions/TransactionUtils.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/IabView.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAnalytics.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsFragment.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsMapper.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsPresenter.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsView.kt
  app/src/main/res/layout/fragment_sandbox.xml
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/BillingAnalytics.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/BrokerApiModule.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/BrokerBdsApi.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/SandboxApi.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/SandboxPayment.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/SandboxResponse.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/SandboxTransaction.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BdsBilling.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BillingRepository.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/BdsRepository.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/repository/RemoteRepository.kt
Labels: Priority

#860 [APPC-4061] Client side caching for oemid
  app/build.gradle.kts
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenPaymentInteractor.kt
  app/src/main/java/com/asfoundation/wallet/billing/paypal/usecases/CreatePaypalTransactionUseCase.kt
  app/src/main/java/com/asfoundation/wallet/billing/sandbox/usecases/CreateSandboxTransactionUseCase.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetFirstPaymentMethodsUseCase.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/use_cases/GetPaymentLinkUseCase.kt
  app/src/main/java/com/asfoundation/wallet/repository/ApproveTransactionValidatorBds.java
  app/src/main/java/com/asfoundation/wallet/repository/BuyTransactionValidatorBds.java
  app/src/main/java/com/asfoundation/wallet/topup/TopUpInteractor.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/RewardsManager.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/localpayments/LocalPaymentInteractor.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/payments/carrier/CarrierInteractor.kt
  app/src/test/java/com/asfoundation/wallet/adyen/AdyenPaymentInteractorTest.kt
  core/analytics/build.gradle.kts
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/AddressService.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/PartnerAddressService.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/BackendApiModule.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/PartnerAttributionApi.kt
  core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OemIdPreferencesDataSource.kt
  legacy/bdsbilling/src/main/java/com/appcoins/wallet/bdsbilling/BdsBilling.kt
Labels: Priority
