Repository Catappult/appcoins-wallet-android, pull requests merged in 2023-11, with the labels that each got.

#802 fix(APPC-3965) Layout bugfixes TopUp
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpFragment.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpPresenter.kt
  app/src/main/java/com/asfoundation/wallet/topup/adyen/AdyenTopUpView.kt
  app/src/main/res/layout-land/error_top_up_layout.xml
  app/src/main/res/layout-land/fragment_adyen_top_up.xml
  app/src/main/res/layout-land/top_up_activity_layout.xml
  app/src/main/res/layout-land/topup_bar_layout.xml
  app/src/main/res/layout/error_top_up_layout.xml
  app/src/main/res/layout/fragment_adyen_top_up.xml
  app/src/main/res/layout/item_payment_method.xml
  app/src/main/res/layout/topup_bar_layout.xml
Labels: Payments v3

#813 [APPC-4005] HotFix Crash on Settings when fetch currencies
  app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsFragment.kt
  app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsPresenter.kt
  app/src/main/java/com/asfoundation/wallet/ui/settings/entry/SettingsView.kt
  feature/change-currency/data/src/main/java/com/appcoins/wallet/feature/changecurrency/data/FiatCurrenciesRepository.kt
  feature/change-currency/ui/src/main/java/com/appcoins/wallet/feature/changecurrency/ui/ChangeFiatCurrencyScreen.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/NoNetworkAlert.kt
Labels: Bug

#829 [APPC-4033] Add expiration date to vip referral code message
  app/src/main/java/com/asfoundation/wallet/promotions/model/PromotionsMapper.kt
  app/src/main/java/com/asfoundation/wallet/promotions/model/VipReferralInfo.kt
  app/src/main/java/com/asfoundation/wallet/promotions/ui/vip_referral/PromotionsVipReferralFragment.kt
  app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
  app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardNavigator.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/VipReferralResponse.kt
  core/utils/android-common/src/main/java/com/appcoins/wallet/core/utils/android_common/DateFormatterUtils.kt
  gradle.properties
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsGamificationComposable.kt
Labels: Priority

#834 Dev Update 3.5.1
  app/build.gradle.kts
Labels: Priority

#844 [APPC-4057] Dana payment new url scheme
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/asfoundation/wallet/ui/iab/BillingWebViewFragment.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/ExternalAppEnum.kt
  app/src/main/res/layout-land/webview_fragment.xml
  app/src/main/res/layout/webview_fragment.xml
  ui/common/src/main/res/drawable/ic_dana.xml
Labels: Priority

#842 [APPC-3973] Recover wallet from web download
  app/src/main/java/com/asfoundation/wallet/app_start/AppStart.kt
  app/src/main/java/com/asfoundation/wallet/app_start/Probes.kt
  app/src/main/java/com/asfoundation/wallet/billing/adyen/AdyenErrorCodeMapper.kt
  app/src/main/java/com/asfoundation/wallet/main/MainActivity.kt
  app/src/main/java/com/asfoundation/wallet/main/MainActivityNavigator.kt
  app/src/main/java/com/asfoundation/wallet/main/MainActivityViewModel.kt
  app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragment.kt
  app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarFragmentNavigator.kt
  app/src/main/java/com/asfoundation/wallet/main/nav_bar/NavBarViewModel.kt
  app/src/main/java/com/asfoundation/wallet/main/use_cases/DeleteCachedGuestWalletUseCase.kt
  app/src/main/java/com/asfoundation/wallet/main/use_cases/GetBonusGuestWalletUseCase.kt
  app/src/main/java/com/asfoundation/wallet/main/use_cases/GetCachedGuestWalletUseCase.kt
  app/src/main/java/com/asfoundation/wallet/onboarding/CachedBackupRepository.kt
  app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingAnalytics.kt
  app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingFragment.kt
  app/src/main/java/com/asfoundation/wallet/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/asfoundation/wallet/onboarding/pending_payment/OnboardingPaymentFragment.kt
  app/src/main/java/com/asfoundation/wallet/onboarding/use_cases/RestoreGuestWalletFlowUseCase.kt
  app/src/main/java/com/asfoundation/wallet/repository/CachedGuestWalletRepository.kt
  app/src/main/res/layout-land/fragment_onboarding.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/navigation/nav_bar_graph.xml
  app/src/main/res/navigation/onboarding_graph.xml
  app/src/test/java/com/asfoundation/wallet/app_start/AppStartUseCaseTest.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/AnalyticsModule.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/BackendApiModule.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/CachedBackupApi.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/api/CachedGuestWalletApi.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedBackupResponse.kt
  core/network/backend/src/main/java/com/appcoins/wallet/core/network/backend/model/CachedGuestWalletResponse.kt
  core/utils/android-common/src/main/java/com/appcoins/wallet/core/utils/android_common/AppUtils.kt
  feature/wallet-info/data/src/main/java/com/appcoins/wallet/feature/walletInfo/data/wallet/AccountWalletService.kt
  ui/common/src/main/res/drawable/ic_guest_wallet_bonus.xml
  ui/common/src/main/res/raw/three_dots_loading.json
  ui/common/src/main/res/values/styles.xml
Labels: Priority
