Repository Catappult/appcoins-wallet-android, pull requests merged in 2024-01, with the labels that each got.

#880 3.11.1 (295)
  app/build.gradle.kts
Labels: Priority

#881 Master update 3.11.1
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/asfoundation/wallet/analytics/IndicativeInitializeWrapper.kt
  app/src/main/java/com/asfoundation/wallet/analytics/InitilizeDataAnalytics.kt
  app/src/main/java/com/asfoundation/wallet/billing/vkpay/usecases/CreateVkPayTransactionUseCase.kt
  app/src/main/java/com/asfoundation/wallet/recover/success/RecoveryWalletSuccessBottomSheetFragment.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyFragment.kt
  app/src/main/java/com/asfoundation/wallet/ui/iab/AppcoinsRewardsBuyPresenter.kt
  app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
  app/src/main/java/com/asfoundation/wallet/wallet/home/HomeViewModel.kt
  app/src/main/java/com/asfoundation/wallet/wallet_reward/GamificationHeaderModel.kt
  app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardFragment.kt
  app/src/main/java/com/asfoundation/wallet/wallet_reward/RewardViewModel.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/AnalyticsLabels.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/IndicativeAnalytics.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/InstallerService.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/InstallerSourceService.kt
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/partners/PartnerAddressService.kt
  core/shared-preferences/src/main/java/com/appcoins/wallet/sharedpreferences/OemIdPreferencesDataSource.kt
  feature/challenge-reward/data/src/main/java/com/appcoins/wallet/feature/challengereward/data/presentation/ChallengeRewardVisibilityViewModel.kt
  feature/challenge-reward/data/src/main/java/com/appcoins/wallet/feature/challengereward/data/presentation/ViewModelProvider.kt
  ui/common/src/main/java/com/appcoins/wallet/ui/common/theme/WalletColors.kt
  ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceCardComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/BalanceCardExpandedComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsActionsComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsGamificationComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/ShimmerSkeletonComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/TransactionsComposable.kt
Labels: Priority

#876 [APPC-4076] Fix preselection of payment methods in Russia
  app/src/main/java/com/asfoundation/wallet/ui/iab/PaymentMethodsAdapter.kt
Labels: Bug

#883 [APPC-4039] Fix plurals strings on Countdown Timer
  ui/common/src/main/res/values-ar/strings.xml
  ui/common/src/main/res/values-bn/strings.xml
  ui/common/src/main/res/values-de/strings.xml
  ui/common/src/main/res/values-el/strings.xml
  ui/common/src/main/res/values-es/strings.xml
  ui/common/src/main/res/values-fa/strings.xml
  ui/common/src/main/res/values-fr/strings.xml
  ui/common/src/main/res/values-hi/strings.xml
  ui/common/src/main/res/values-hu/strings.xml
  ui/common/src/main/res/values-in/strings.xml
  ui/common/src/main/res/values-it/strings.xml
  ui/common/src/main/res/values-ja/strings.xml
  ui/common/src/main/res/values-ko/strings.xml
  ui/common/src/main/res/values-mr/strings.xml
  ui/common/src/main/res/values-ms/strings.xml
  ui/common/src/main/res/values-my/strings.xml
  ui/common/src/main/res/values-nl/strings.xml
  ui/common/src/main/res/values-pa/strings.xml
  ui/common/src/main/res/values-pl/strings.xml
  ui/common/src/main/res/values-pt-rBR/strings.xml
  ui/common/src/main/res/values-pt/strings.xml
  ui/common/src/main/res/values-ro/strings.xml
  ui/common/src/main/res/values-ru/strings.xml
  ui/common/src/main/res/values-sr/strings.xml
  ui/common/src/main/res/values-th/strings.xml
  ui/common/src/main/res/values-tr/strings.xml
  ui/common/src/main/res/values-uk/strings.xml
  ui/common/src/main/res/values-vi/strings.xml
  ui/common/src/main/res/values-zh-rCN/strings.xml
  ui/common/src/main/res/values-zh-rTW/strings.xml
  ui/common/src/main/res/values/strings.xml
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/PromotionsCardComposable.kt
Labels: Strings, Bug

#873 [APPC-4091] Fix layout differences from design
  app/src/main/java/com/asfoundation/wallet/manage_wallets/ManageWalletFragment.kt
  app/src/main/java/com/asfoundation/wallet/topup/TopUpFragment.kt
  app/src/main/java/com/asfoundation/wallet/transfers/TransferFundsFragment.kt
  app/src/main/java/com/asfoundation/wallet/ui/gamification/GamificationMapper.kt
  app/src/main/java/com/asfoundation/wallet/wallet/home/HomeFragment.kt
  app/src/main/res/layout/current_level_card.xml
  app/src/main/res/layout/fragment_adyen_top_up.xml
  app/src/main/res/layout/fragment_create_wallet_dialog_layout.xml
  app/src/main/res/layout/fragment_subscription_cancel.xml
  app/src/main/res/layout/fragment_subscription_cancel_success.xml
  app/src/main/res/layout/fragment_subscription_list.xml
  app/src/main/res/layout/fragment_top_up.xml
  app/src/main/res/layout/layout_no_subscriptions.xml
  app/src/main/res/layout/manage_wallet_balance_bottom_sheet_layout.xml
  app/src/main/res/layout/manage_wallet_bottom_sheet_layout.xml
  app/src/main/res/layout/manage_wallet_name_bottom_sheet_layout.xml
  ui/common/src/main/res/drawable/gamification_earth.xml
  ui/common/src/main/res/drawable/gamification_europa.xml
  ui/common/src/main/res/drawable/gamification_jupiter.xml
  ui/common/src/main/res/drawable/gamification_mars.xml
  ui/common/src/main/res/drawable/gamification_moon.xml
  ui/common/src/main/res/drawable/gamification_neptune.xml
  ui/common/src/main/res/drawable/gamification_phobos.xml
  ui/common/src/main/res/drawable/gamification_saturn.xml
  ui/common/src/main/res/drawable/gamification_titan.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_blue.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_blue_reached.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_brown.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_brown_reached.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_green.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_green_reached.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_red.xml
  ui/common/src/main/res/drawable/gamification_unknown_planet_red_reached.xml
  ui/common/src/main/res/drawable/gamification_uranus.xml
  ui/common/src/main/res/drawable/ic_plus_v3.xml
  ui/common/src/main/res/drawable/pull_up_home_bar.xml
  ui/common/src/main/res/drawable/rounded_dialog_black.xml
  ui/common/src/main/res/drawable/rounded_dialog_dark.xml
  ui/common/src/main/res/values/styles.xml
  ui/widgets/src/aptoide/java/com/appcoins/wallet/ui/widgets/GamesBundleComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/RewardsGamificationComposable.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/WalletTextFieldView.kt
  ui/widgets/src/main/java/com/appcoins/wallet/ui/widgets/component/Button.kt
Labels: Bug

#891 [APPC-4145] IAP layout fixes
  app/src/main/java/com/asfoundation/wallet/ui/iab/IabActivity.kt
  app/src/main/res/layout-land/adyen_credit_card_layout.xml
  app/src/main/res/layout-land/iab_error_layout.xml
  app/src/main/res/layout-land/support_error_layout.xml
  app/src/main/res/layout/activity_iab.xml
  app/src/main/res/layout/adyen_credit_card_layout.xml
  app/src/main/res/layout/adyen_credit_card_pre_selected.xml
  app/src/main/res/layout/dialog_buy_buttons_adyen_error.xml
  app/src/main/res/layout/fragment_paypal.xml
  app/src/main/res/layout/fragment_paypal_topup.xml
  app/src/main/res/layout/iab_error_layout.xml
Labels: Priority, Bug

#816 [ESKL-371] Package version ban
  core/analytics/src/main/java/com/appcoins/wallet/core/analytics/analytics/legacy/SkillsAnalytics.kt
  core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/model/EskillsPaymentData.kt
  core/network/eskills/src/main/java/com/appcoins/wallet/core/network/eskills/model/TicketRequest.kt
  legacy/skills/src/main/java/cm/aptoide/skills/SkillsFragment.kt
  legacy/skills/src/main/java/cm/aptoide/skills/SkillsViewModel.kt
  legacy/skills/src/main/java/cm/aptoide/skills/model/Ticket.kt
  legacy/skills/src/main/java/cm/aptoide/skills/repository/TicketApiMapper.kt
  legacy/skills/src/main/java/cm/aptoide/skills/repository/TicketRepository.kt
  legacy/skills/src/main/java/cm/aptoide/skills/usecase/RetrievePackageVersionUseCase.kt
  legacy/skills/src/main/java/cm/aptoide/skills/usecase/ValidateUrlUseCase.kt
Labels: E-Skills

#896 Revert "[APPC-4084] Different merchants support for VK Pay"
  app/src/main/java/com/asfoundation/wallet/billing/paypal/usecases/CreatePaypalTransactionUseCase.kt
  app/src/main/java/com/asfoundation/wallet/billing/vkpay/VkPaymentIABFragment.kt
  app/src/main/java/com/asfoundation/wallet/billing/vkpay/repository/VkPayRepository.kt
  app/src/main/java/com/asfoundation/wallet/billing/vkpay/usecases/CreateVkPayTransactionUseCase.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentFragment.kt
  app/src/main/java/com/asfoundation/wallet/onboarding_new_payment/vkPayment/OnboardingVkPaymentViewModel.kt
  app/src/main/java/com/asfoundation/wallet/topup/vkPayment/VkPaymentTopUpFragment.kt
  convention/src/main/java/com/appcoins/wallet/convention/extensions/BuildConfigExtension.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/api/broker/VkPayApi.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/VkPayTransaction.kt
  core/network/microservices/src/main/java/com/appcoins/wallet/core/network/microservices/model/VkTransactionResponse.kt
Labels: Priority
